<a href="https://colab.research.google.com/github/Psousace/Curso_TradingDados/blob/main/16-Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center><img src = "https://github.com/Trading-com-Dados/pmf/blob/main/logotipo-trading-com-dados.svg?raw=true" width = "200">

# **Fundamentos da Programação em Python**


## Numpy

In [ ]:
import numpy as np

O principal tipo de objeto que criamos com a numpy é o 'array'

Para criar arrays, temos diversas funções diferentes, cada um servido a um propósito específico

Por exemplo, podemos criar arrays que contém apenas zeros

In [ ]:
np.zeros(5, dtype = int)

array([0, 0, 0, 0, 0])

In [ ]:
zeros = np.zeros(5, dtype = int)

In [ ]:
type(zeros)

numpy.ndarray

In [ ]:
zeros

array([0, 0, 0, 0, 0])

Conceito de atributo

In [ ]:
zeros.shape

(5,)

In [ ]:
zeros.shape = (5,1)

In [ ]:
zeros

array([[0],
       [0],
       [0],
       [0],
       [0]])

Da mesma forma que criamos um vetor de zeros, podemos criar um contendo apenas 'uns'

In [ ]:
np.ones(5, dtype = int)

array([1, 1, 1, 1, 1])

Podemos criar vetores vazios

In [ ]:
np.empty(9)

array([2.28444255e-316, 0.00000000e+000, 1.01199493e+261, 2.31633993e-152,
       1.05879250e-153, 3.54984507e+180, 9.81570639e-153, 7.20100776e+252,
       7.11454530e-322])

Podemos criar um array determinando início, fim e número de componentes

In [ ]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

Podemos especificar manualmente os elementos do array

In [ ]:
np.array(0)

array(0)

In [ ]:
np.array(10)

array(10)

In [ ]:
lista_numeros = [0,1,2,3]

In [ ]:
np.array(lista_numeros)

array([0, 1, 2, 3])

In [ ]:
papeis = ['ABEV3', 'PETR4', 'VALE3', 'BBDC4', 'PRIO3']

In [ ]:
np.array(papeis)

array(['ABEV3', 'PETR4', 'VALE3', 'BBDC4', 'PRIO3'], dtype='<U5')

In [ ]:
papeis_array = np.array(papeis)

In [ ]:
papeis_array

array(['ABEV3', 'PETR4', 'VALE3', 'BBDC4', 'PRIO3'], dtype='<U5')

In [ ]:
papeis_array[0]

'ABEV3'

In [ ]:
lista = [1,2,3,4,5]

In [ ]:
np.array([lista, papeis])

array([['1', '2', '3', '4', '5'],
       ['ABEV3', 'PETR4', 'VALE3', 'BBDC4', 'PRIO3']], dtype='<U21')

In [ ]:
i = np.array([lista, papeis])

In [ ]:
i[0]

array(['1', '2', '3', '4', '5'], dtype='<U21')

In [ ]:
i[1]

array(['ABEV3', 'PETR4', 'VALE3', 'BBDC4', 'PRIO3'], dtype='<U21')

In [ ]:
i[0][0]

'1'

In [ ]:
i[1][0]

'ABEV3'

Muito parecido com listas

Operações matemáticas

In [ ]:
a = np.array([10,20,100,200,500])
b = np.array([3,4,5,6,7])

In [ ]:
a + b

array([ 13,  24, 105, 206, 507])

In [ ]:
np.add(a, b)

array([ 13,  24, 105, 206, 507])

In [ ]:
a - b

array([  7,  16,  95, 194, 493])

In [ ]:
np.subtract(a, b)

array([  7,  16,  95, 194, 493])

In [ ]:
a*b

array([  30,   80,  500, 1200, 3500])

In [ ]:
np.multiply(a, b)

array([  30,   80,  500, 1200, 3500])

In [ ]:
a/b

array([ 3.33333333,  5.        , 20.        , 33.33333333, 71.42857143])

In [ ]:
np.divide(a, b)

array([ 3.33333333,  5.        , 20.        , 33.33333333, 71.42857143])

Funções estatísticas

In [ ]:
precos = np.array([22.14, 23.56, 23.89])

In [ ]:
precos.min()

22.14

In [ ]:
np.min(precos)

22.14

In [ ]:
np.amin(precos)

22.14

In [ ]:
np.max(precos)

23.89

In [ ]:
np.amax(precos)

23.89

In [ ]:
np.median(precos)

23.56

In [ ]:
np.mean(precos)

23.19666666666667

In [ ]:
np.std(precos)

0.7592247507966411

In [ ]:
np.var(precos)

0.5764222222222217